### ISSUE TITLE
Fails to build on Windows

### ISSUE THREAD

**Issue by johnschult** [wadey/node-microtime#34]
I am including `node-microtime` in [johnschult:microtime](https://github.com/johnschult/meteor-microtime) as a package to run on the server in Meteor. Published packages need to build on all architectures supported by Meteor. I had no problems until I tried to build it for Windows:

```
npm ERR! node v0.10.36
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! microtime@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the microtime@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
```

Any idea how to fix this?

**Comment by wadey** [comment]
Can you paste the full output from npm? I run Windows builds for nodejs 0.8 - iojs 3.0.0 on Appveyor and they are all passing for 2.0.0: https://ci.appveyor.com/project/WadeSimmons/node-microtime/branch/master

**Comment by johnschult** [comment]
I updated the output above to include the first 2 lines I missed...  Looks like it is building for `node v0.10.36`.

**Comment by jedmao** [comment]
@johnschult I also had problems installing on Windows, but installing Python 2.7 fixed it for me.

**Comment by jedmao** [comment]
@wadey it's also failing to build on Linux. See https://travis-ci.org/cssnext/cssnext/builds/79088034

**Comment by wadey** [comment]
@jedmao this is a known issue with Travis-CI (https://github.com/travis-ci/travis-ci/issues/1379), iojs requires GCC 4.8. Here is a very simple Travis CI config change that works:

- https://github.com/wadey/node-microtime/blob/587e661/.travis.yml#L2-L9

and the corresponding travis CI build for this exact config: https://travis-ci.org/wadey/node-microtime/builds/79269878

**Comment by Hikariii** [comment]
Same kind of error here:

```
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.11.13
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! microtime@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
```

Also happens when installing 1.5.0

```
> microtime@1.5.0 install /home/....
> node-gyp rebuild

make: Entering directory `/home/.../node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:9:0:
../node_modules/nan/nan.h: In function ‘void Nan::SetCounterFunction(v8::CounterLookupCallback)’:
../node_modules/nan/nan.h:447:32: error: ‘class v8::Isolate’ has no member named ‘SetCounterFunction’
     v8::Isolate::GetCurrent()->SetCounterFunction(cb);
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::SetCreateHistogramFunction(v8::CreateHistogramCallback)’:
../node_modules/nan/nan.h:452:32: error: ‘class v8::Isolate’ has no member named ‘SetCreateHistogramFunction’
     v8::Isolate::GetCurrent()->SetCreateHistogramFunction(cb);
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::SetAddHistogramSampleFunction(v8::AddHistogramSampleCallback)’:
../node_modules/nan/nan.h:457:32: error: ‘class v8::Isolate’ has no member named ‘SetAddHistogramSampleFunction’
     v8::Isolate::GetCurrent()->SetAddHistogramSampleFunction(cb);
                                ^
../node_modules/nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
../node_modules/nan/nan.h:468:39: error: ‘class v8::Isolate’ has no member named ‘IdleNotification’
     return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                       ^
../node_modules/nan/nan.h: In function ‘void Nan::LowMemoryNotification()’:
../node_modules/nan/nan.h:473:32: error: ‘class v8::Isolate’ has no member named ‘LowMemoryNotification’
     v8::Isolate::GetCurrent()->LowMemoryNotification();
                                ^
../node_modules/nan/nan.h: In function ‘void Nan::ContextDisposedNotification()’:
../node_modules/nan/nan.h:477:32: error: ‘class v8::Isolate’ has no member named ‘ContextDisposedNotification’
     v8::Isolate::GetCurrent()->ContextDisposedNotification();
                                ^
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory `/home/.../node_modules/microtime/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/.../node_modules/microtime
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
```

But not when installing 1.4.2

**Comment by wadey** [comment]
@Hikariii Node v0.11.13 is not a supported build (0.11.x is an unstable branch). Please update to v0.11.16 or v0.12.x.

**Comment by Hikariii** [comment]
ah thnx

**Comment by urbanappetite** [comment]
Seeing the same issue with 4.X.X - let me know if you need more logs.

**Comment by wadey** [comment]
Yeah, I need more logs. 4.x.x is building fine on Appveyor (which is Windows): https://ci.appveyor.com/project/WadeSimmons/node-microtime/build/51/job/urn3awvy5l8li5nw

I don't have a windows box myself to investigate further.

**Comment by yosheeck** [comment]
So small package, and to actually use it I needed to download&install the ~10GB of m$ sh**t. That makes no sense. Why there is not simple binary included ? It will safe soooo much time.

**Comment by jedmao** [comment]
Windows 10 here and everything installs fine. Granted, I also have [Visual Studio Community 2015](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) installed, which is free.

```
z:\Documents\GitHub>node -v
v4.2.1
```

```
z:\Documents\GitHub>python --version
Python 2.7.10
```

```
z:\Documents\GitHub>npm install microtime
npm WARN package.json GitHub@1.0.0 No description
npm WARN package.json GitHub@1.0.0 No repository field.
npm WARN package.json GitHub@1.0.0 No README data
\
> microtime@2.0.0 install z:\Documents\GitHub\node_modules\microtime
> node-gyp rebuild


z:\Documents\GitHub\node_modules\microtime>if not defined npm_config_node_gyp (n
ode "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  microtime.cc
  win_delay_load_hook.c
     Creating library z:\Documents\GitHub\node_modules\microtime\build\Release\
  microtime.lib and object z:\Documents\GitHub\node_modules\microtime\build\Rel
  ease\microtime.exp
  Generating code
  Finished generating code
  microtime.vcxproj -> z:\Documents\GitHub\node_modules\microtime\build\Release
  \\microtime.node
microtime@2.0.0 node_modules\microtime
├── bindings@1.2.1
└── nan@2.0.9
```

**Comment by mikemaccana** [comment]
Thanks @wadey ! 

CircleCI users: here's the same fix https://discuss.circleci.com/t/using-node-js-4-0-on-circleci/26

I wish the CI vendors would install the right compiler in their node images. Both Travis and Circle should have sorted this out by default.

**Comment by wadey** [comment]
Closing this ticket as it seems like most people have microtime working with Windows. If anyone runs into issues please open a new ticket with details.
