### ISSUE TITLE
Fails to build on current node

### ISSUE THREAD

**Issue by mikemaccana** [wadey/node-microtime#38]
On node v4.1.1:

    npm install

    > microtime@1.2.0 install /Users/me/Documents/myapp/node_modules/microtime
    > node-gyp rebuild

      CXX(target) Release/obj.target/microtime/src/microtime.o
    In file included from ../src/microtime.cc:11:
    In file included from ../../nan/nan.h:74:
    In file included from ../../nan/nan_new.h:181:
    ../../nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
      return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
             ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
    /Users/me/.node-gyp/4.1.1/include/node/v8.h:4675:3: note: 'New' declared here
      static Local<Signature> New(
      ^
    In file included from ../src/microtime.cc:11:
    ../../nan/nan.h:165:25: error: redefinition of '_NanEnsureLocal'
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:160:25: note: previous definition is here
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                            ^
    ../../nan/nan.h:253:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:258:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Primitive]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:263:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:268:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Boolean]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:500:13: error: no member named 'smalloc' in namespace 'node'
        , node::smalloc::FreeCallback callback
          ~~~~~~^
    ../../nan/nan.h:511:12: error: no matching function for call to 'New'
        return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
               ^~~~~~~~~~~~~~~~~
    /Users/me/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int')
          to 'enum encoding' for 3rd argument
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    /Users/me/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    /Users/me/.node-gyp/4.1.1/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                           ^
    /Users/me/.node-gyp/4.1.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    In file included from ../src/microtime.cc:11:
    ../../nan/nan.h:515:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
        return node::Buffer::New(v8::Isolate::GetCurrent(), size);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/me/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
          'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
    class Local {
          ^
    /Users/me/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
          'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
    class Local {
          ^
    /Users/me/.node-gyp/4.1.1/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/me/.node-gyp/4.1.1/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
      V8_INLINE Local(S* that)
                ^
    In file included from ../src/microtime.cc:11:
    ../../nan/nan.h:522:26: error: no member named 'Use' in namespace 'node::Buffer'
        return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
               ~~~~~~~~~~~~~~^
    ../../nan/nan.h:1339:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Function]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:1354:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(node::MakeCallback(
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Value]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:1427:12: error: no matching function for call to '_NanEnsureLocal'
        return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:239:43: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                              ^~~~~~~~~~~~~~~
    ../../nan/nan.h:165:25: note: candidate template ignored: substitution failure [with T = v8::Object]
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../src/microtime.cc:51:36: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(node::ErrnoException(errno, "gettimeofday"));
                                       ^
    /Users/me/.node-gyp/4.1.1/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                    inline v8::Local<v8::Value> ErrnoException(
                                                ^
    /Users/me/.node-gyp/4.1.1/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                                             ^
    ../src/microtime.cc:64:36: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(node::ErrnoException(errno, "gettimeofday"));
                                       ^
    /Users/me/.node-gyp/4.1.1/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                    inline v8::Local<v8::Value> ErrnoException(
                                                ^
    /Users/me/.node-gyp/4.1.1/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                                             ^
    ../src/microtime.cc:77:36: warning: 'ErrnoException' is deprecated: Use UVException(isolate, ...) [-Wdeprecated-declarations]
            return NanThrowError(node::ErrnoException(errno, "gettimeofday"));
                                       ^
    /Users/me/.node-gyp/4.1.1/include/node/node.h:100:45: note: 'ErrnoException' has been explicitly marked deprecated here
                    inline v8::Local<v8::Value> ErrnoException(
                                                ^
    /Users/me/.node-gyp/4.1.1/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                                             ^
    3 warnings and 13 errors generated.
    make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/me/Documents/myapp/node_modules/microtime
    gyp ERR! node -v v4.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok

    npm ERR! Darwin 14.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v4.1.1
    npm ERR! npm  v3.3.4
    npm ERR! code ELIFECYCLE
    npm ERR! microtime@1.2.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the microtime@1.2.0 install script 'nodea-gyp rebuild'.
    npm ERR! This is most likely a problem with the microtime package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls microtime
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/me/Documents/myapp/npm-debug.log

**Comment by wadey** [comment]
Please update to microtime 1.5.x. 1.2.x is not supported on Node 4.

**Comment by mikemaccana** [comment]
Sorry @wadey , not sure how I ended up on such an old version. Can confirm @latest is fine, sorry for wasting you time.

**Comment by wadey** [comment]
No worries, it happens.
