### ISSUE TITLE
Error install microtime 

### ISSUE THREAD

**Issue by capo349** [wadey/node-microtime#45]
C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0>npm install microtime@2.1.1

 microtime@2.1.1 install C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0\node_modules\microtime

> node-gyp rebuild

C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0\node_modules\microtime>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-g
yp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar la compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVers
ion or PlatformToolset may be set to an invalid version number. [C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0\node_modules\microtime\build\microtime.vcxproj]
TRACKER : error TRK0005: no se encontró: "CL.exe". El sistema no puede encontrar el archivo especificado. [C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0\node_mod
ules\microtime\build\microtime.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0\node_modules\microtime
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "microtime@2.1.1"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! microtime@2.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@2.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs microtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Soporte\Documents\Webstorm\Modulo_Serial_CapaRaspberry_V2.0\npm-debug.log

**Comment by wadey** [comment]
The key error line is:

    TRACKER : error TRK0005: no se encontró: "CL.exe". El sistema no puede encontrar el archivo especificado. 

It looks like your error is the same as this issue, try the solution listed there:

http://stackoverflow.com/questions/33716369/error-trk0005-failed-to-locate-cl-exe/33716573

>  I went into Visual Studio and created a Visual C++ project, which installed several libraries. npm install worked after that.

**Comment by wadey** [comment]
Closing due to no activity. Assuming it was due to the link mentioned.
