### ISSUE TITLE
build fail v2.1.5 on linux

### ISSUE THREAD

**Issue by xilixinluo** [wadey/node-microtime#52]
There is something wrong on my project. the install from source failed for ? 
`
node-pre-gyp http GET https://github.com/wadey/node-microtime/releases/download/v2.1.5/node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/wadey/node-microtime/releases/download/v2.1.5/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/wadey/node-microtime/releases/download/v2.1.5/node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for microtime@2.1.5 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/wadey/node-microtime/releases/download/v2.1.5/node-v57-linux-x64.tar.gz
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "" does not have permission to access the dev dir "/root/.node-gyp/8.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp http GET http://nodejs.org/dist/v8.0.0/node-v8.0.0-headers.tar.gz
gyp http 200 http://nodejs.org/dist/v8.0.0/node-v8.0.0-headers.tar.gz
gyp http GET http://nodejs.org/dist/v8.0.0/SHASUMS256.txt
gyp http 200 http://nodejs.org/dist/v8.0.0/SHASUMS256.txt
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build'
make: *** No rule to make target `../.node-gyp/8.0.0/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/eva.li/.nvm/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 2.6.32-358.23.2.el6.x86_64
gyp ERR! command "/home/eva.li/.nvm/v8.0.0/bin/node" "/home/eva.li/.nvm/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build/Release/microtime.node" "--module_name=microtime" "--module_path=/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build/Release"
gyp ERR! cwd /home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/eva.li/.nvm/v8.0.0/bin/node /home/eva.li/.nvm/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build/Release/microtime.node --module_name=microtime --module_path=/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Linux 2.6.32-358.23.2.el6.x86_64
node-pre-gyp ERR! command "/home/eva.li/.nvm/v8.0.0/bin/node" "/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/home/eva.li/.nvm/v8.0.0/bin/node /home/eva.li/.nvm/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build/Release/microtime.node --module_name=microtime --module_path=/home/q/www/yshow.corp.qunar.com/webapp/node_modules/microtime/build/Release' (1)
npm ERR! Cannot read property 'type' of undefined
`

**Comment by ben-turner** [comment]
Looks to me that it was never built for Linux. https://github.com/wadey/node-microtime/releases/tag/v2.1.5

**Comment by wadey** [comment]
I'm going to release 2.1.6 tomorrow with prebuilt Linux binaries.

**Comment by ben-turner** [comment]
This release broke a lot of things. Many packages depend on it with `^2.1.something_that_works`. By pushing this patch version that is not backwards-compatible you broke everything that depends on it that runs on Linux. The biggest issue that I can find is that this broke Webpack on Linux.

**Comment by ben-turner** [comment]
I see now that it's supposed to fall back to building from source, but that build is failing due to node-gyp. This failure happens on npm, I don't know about yarn.

**Comment by wadey** [comment]
I'm switching over to `prebuilt-install` for the next release, the same thing that other large projects like leveldown use, so should fix it
