### ISSUE TITLE
'npm rebuild' failed after upgrading node

### ISSUE THREAD

**Issue by yarons** [wadey/node-microtime#53]
[npm-debug.txt](https://github.com/wadey/node-microtime/files/1156021/npm-debug.txt)

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
gyp ERR! command "/usr/local/n/versions/node/8.0.0/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/rtapp/node_modules/graygelf/node_modules/microtime
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Linux 3.16.0-0.bpo.4-amd64
npm ERR! argv "/usr/local/n/versions/node/8.0.0/bin/node" "/usr/bin/npm" "rebuild" "microtime"
npm ERR! node v8.0.0
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! microtime@1.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@1.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs microtime
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/rtapp/npm-debug.log
```

**Comment by wadey** [comment]
> npm ERR! microtime@1.5.0 install: `node-gyp rebuild`

Please update to the latest version and see if you are still having this issue. Latest version is `2.1.6`.

**Comment by wadey** [comment]
It looks like the package you are using which depends on microtime is `graygelf`. The latest version of that package depends on `microtime@^2.0.1` which should work:

https://github.com/wavded/graygelf/blob/1.0.2/package.json#L31

**Comment by yarons** [comment]
Thank you!
