### ISSUE TITLE
TravisCI fails to build microtime-2.1.7 on iojs

### ISSUE THREAD

**Issue by saschat** [wadey/node-microtime#58]
On my travis setup for [memjs](https://github.com/memcachier/memjs) it fails to build `microtime-2.1.7` for `iojs`. I have checked #33, #34, and #36 but this seems to be different. Here is the relevant travis log output:
```
> microtime@2.1.7 install /home/travis/build/memcachier/memjs/node_modules/microtime
> prebuild-install || node-gyp rebuild
/home/travis/build/memcachier/memjs/node_modules/microtime/node_modules/prebuild-install/node_modules/simple-get/node_modules/decompress-response/index.js:6
module.exports = response => {
                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/memcachier/memjs/node_modules/microtime/node_modules/prebuild-install/node_modules/simple-get/index.js:8:26)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
make: Entering directory `/home/travis/build/memcachier/memjs/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../node_modules/nan/nan.h:197:0,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::DefineOwnProperty(v8::Local<v8::Object>, v8::Local<v8::String>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘DefineOwnProperty’
   return obj->DefineOwnProperty(isolate->GetCurrentContext(), key, value,
               ^
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory `/home/travis/build/memcachier/memjs/node_modules/microtime/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.14.12-041412-generic
gyp ERR! command "/home/travis/.nvm/versions/io.js/v3.3.1/bin/iojs" "/home/travis/.nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/memcachier/memjs/node_modules/microtime
gyp ERR! node -v v3.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN engine esrecurse@4.2.1: wanted: {"node":">=4.0"} (current: {"node":"3.3.1","npm":"2.14.3"})
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v3.3.1/bin/iojs" "/home/travis/.nvm/versions/io.js/v3.3.1/bin/npm" "install"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! microtime@2.1.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microtime@2.1.7 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
```

This is the config:
```
{
  "language": "node_js",
  "sudo": false,
  "node_js": "iojs",
  "env": "CXX=g++-4.8",
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "g++-4.8"
      ]
    }
  },
  "os": "linux",
  "group": "stable",
  "dist": "trusty"
}
```

**Comment by wadey** [comment]
It looks like the issue is prebuild-install not supporting iojs 3.x. I think only Node 4+ is supported. You should open the ticket with prebuild-install

**Comment by saschat** [comment]
Thanks for the response! If this is the case, we can close this.
