### ISSUE TITLE
Cannot install in M1 Mac

### ISSUE THREAD

**Issue by adaptive-adam** [wadey/node-microtime#67]
When trying to run npm i I am getting the following error.

Please consider upgrading to node-gyp@9.x.x 

```
0 verbose cli [
0 verbose cli   '/Users/adamkoncz/.nvm/versions/node/v16.13.2/bin/node',
0 verbose cli   '/Users/adamkoncz/.nvm/versions/node/v16.13.2/bin/npm',
0 verbose cli   'i',
0 verbose cli   'microtime'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/adamkoncz/Documents/work/Local/Solana Tests/untitled folder/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/adamkoncz/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/adamkoncz/.nvm/versions/node/v16.13.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 4ms
19 timing npm:load:configload Completed in 4ms
20 timing npm:load:setTitle Completed in 5ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 1ms
23 timing npm:load:cleanupLog Completed in 1ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 12ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 1ms
29 timing idealTree:init Completed in 6ms
30 timing idealTree:userRequests Completed in 1ms
31 silly idealTree buildDeps
32 silly fetch manifest microtime@*
33 http fetch GET 200 https://registry.npmjs.org/microtime 6ms (cache hit)
34 silly placeDep ROOT microtime@3.0.0 OK for: test@1.0.0 want: *
35 silly fetch manifest node-addon-api@^1.2.0
36 silly fetch manifest node-gyp-build@^3.8.0
37 http fetch GET 200 https://registry.npmjs.org/node-addon-api 3ms (cache hit)
38 http fetch GET 200 https://registry.npmjs.org/node-gyp-build 6ms (cache hit)
39 timing idealTree:#root Completed in 16ms
40 silly placeDep ROOT node-addon-api@1.7.2 OK for: microtime@3.0.0 want: ^1.2.0
41 silly placeDep ROOT node-gyp-build@3.9.0 OK for: microtime@3.0.0 want: ^3.8.0
42 timing idealTree:node_modules/microtime Completed in 1ms
43 timing idealTree:node_modules/node-addon-api Completed in 0ms
44 timing idealTree:node_modules/node-gyp-build Completed in 0ms
45 timing idealTree:buildDeps Completed in 17ms
46 timing idealTree:fixDepFlags Completed in 0ms
47 timing idealTree Completed in 25ms
48 timing reify:loadTrees Completed in 26ms
49 timing reify:diffTrees Completed in 0ms
50 silly reify moves {}
51 timing reify:retireShallow Completed in 1ms
52 timing reify:createSparse Completed in 0ms
53 timing reify:loadBundles Completed in 0ms
54 silly audit bulk request {
54 silly audit   microtime: [ '3.0.0' ],
54 silly audit   'node-addon-api': [ '1.7.2' ],
54 silly audit   'node-gyp-build': [ '3.9.0' ]
54 silly audit }
55 timing reifyNode:node_modules/node-gyp-build Completed in 23ms
56 timing reifyNode:node_modules/microtime Completed in 27ms
57 timing reifyNode:node_modules/node-addon-api Completed in 30ms
58 timing reify:unpack Completed in 30ms
59 timing reify:unretire Completed in 0ms
60 timing build:queue Completed in 0ms
61 timing build:link:node_modules/node-gyp-build Completed in 1ms
62 timing build:link Completed in 1ms
63 info run microtime@3.0.0 install node_modules/microtime node-gyp-build
64 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 316ms
65 timing auditReport:getReport Completed in 317ms
66 silly audit report {}
67 timing auditReport:init Completed in 0ms
68 timing reify:audit Completed in 317ms
69 info run microtime@3.0.0 install { code: 1, signal: null }
70 timing reify:rollback:createSparse Completed in 10ms
71 timing reify:rollback:retireShallow Completed in 0ms
72 timing command:install Completed in 761ms
73 verbose stack Error: command failed
73 verbose stack     at ChildProcess.<anonymous> (/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
73 verbose stack     at ChildProcess.emit (node:events:390:28)
73 verbose stack     at maybeClose (node:internal/child_process:1064:16)
73 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
74 verbose pkgid microtime@3.0.0
75 verbose cwd /Users/adamkoncz/Documents/work/Local/Solana Tests/untitled folder
76 verbose Darwin 21.4.0
77 verbose argv "/Users/adamkoncz/.nvm/versions/node/v16.13.2/bin/node" "/Users/adamkoncz/.nvm/versions/node/v16.13.2/bin/npm" "i" "microtime"
78 verbose node v16.13.2
79 verbose npm  v8.1.2
80 error code 1
81 error path /Users/adamkoncz/Documents/work/Local/Solana Tests/untitled folder/node_modules/microtime
82 error command failed
83 error command sh -c node-gyp-build
84 error CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
84 error   LIBTOOL-STATIC Release/nothing.a
84 error   CXX(target) Release/obj.target/microtime/src/microtime.o
85 error gyp info it worked if it ends with ok
85 error gyp info using node-gyp@8.3.0
85 error gyp info using node@16.13.2 | darwin | arm64
85 error gyp info find Python using Python version 3.9.9 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
85 error gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
85 error gyp info spawn args [
85 error gyp info spawn args   '/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
85 error gyp info spawn args   'binding.gyp',
85 error gyp info spawn args   '-f',
85 error gyp info spawn args   'make',
85 error gyp info spawn args   '-I',
85 error gyp info spawn args   '/Users/adamkoncz/Documents/work/Local/Solana Tests/untitled folder/node_modules/microtime/build/config.gypi',
85 error gyp info spawn args   '-I',
85 error gyp info spawn args   '/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
85 error gyp info spawn args   '-I',
85 error gyp info spawn args   '/Users/adamkoncz/Library/Caches/node-gyp/16.13.2/include/node/common.gypi',
85 error gyp info spawn args   '-Dlibrary=shared_library',
85 error gyp info spawn args   '-Dvisibility=default',
85 error gyp info spawn args   '-Dnode_root_dir=/Users/adamkoncz/Library/Caches/node-gyp/16.13.2',
85 error gyp info spawn args   '-Dnode_gyp_dir=/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp',
85 error gyp info spawn args   '-Dnode_lib_file=/Users/adamkoncz/Library/Caches/node-gyp/16.13.2/<(target_arch)/node.lib',
85 error gyp info spawn args   '-Dmodule_root_dir=/Users/adamkoncz/Documents/work/Local/Solana Tests/untitled folder/node_modules/microtime',
85 error gyp info spawn args   '-Dnode_engine=v8',
85 error gyp info spawn args   '--depth=.',
85 error gyp info spawn args   '--no-parallel',
85 error gyp info spawn args   '--generator-output',
85 error gyp info spawn args   'build',
85 error gyp info spawn args   '-Goutput_dir=.'
85 error gyp info spawn args ]
85 error gyp info spawn make
85 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
85 error warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
85 error clang: error: no such file or directory: 'Tests/untitled'
85 error clang: error: no such file or directory: 'folder/node_modules/node-addon-api'
85 error make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
85 error gyp ERR! build error
85 error gyp ERR! stack Error: `make` failed with exit code: 2
85 error gyp ERR! stack     at ChildProcess.onExit (/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
85 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
85 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
85 error gyp ERR! System Darwin 21.4.0
85 error gyp ERR! command "/Users/adamkoncz/.nvm/versions/node/v16.13.2/bin/node" "/Users/adamkoncz/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
85 error gyp ERR! cwd /Users/adamkoncz/Documents/work/Local/Solana Tests/untitled folder/node_modules/microtime
85 error gyp ERR! node -v v16.13.2
85 error gyp ERR! node-gyp -v v8.3.0
85 error gyp ERR! not ok
86 verbose exit 1

```

**Comment by johnkoehn** [comment]
Same problem, it would be awesome to get a build of this that works on m1

**Comment by hect1c** [comment]
Same here. I got the problem when trying to install https://www.npmjs.com/package/broadcast-channel which has a dependency on `microtime`.

**Comment by zouhangwithsweet** [comment]
same error
node_modules/.pnpm/secp256k1@3.8.0/node_modules/secp256k1: Running install script...
node_modules/.pnpm/microtime@3.0.0/node_modules/microtime: Running install script...
 ELIFECYCLE  Command failed.

**Comment by nickfujita** [comment]
Took a stab at this, but this is my first time updating a napi repo, so would appreciate anyone looking at it who is able. With the updates I'm able to build a universal build locally.

https://github.com/wadey/node-microtime/pull/68

**Comment by wadey** [comment]
I will look at this tomorrow and try to get I merged. Thank you everyone!

**Comment by nickfujita** [comment]
Thank you @wadey !

I'm not sure what is better, to just create an additional darwin-arm64 build or the universal x64+arm64

**Comment by wadey** [comment]
I've published microtime 3.1.0, can everyone test it out and report back any issues? Thank you!

**Comment by wadey** [comment]
Node v8 has been out of maintenance since 2019, can you upgrade to a newer node?

**Comment by Beace** [comment]
Node8 must be used for some special reasons...I temporarily locked the version to 3.0.0

**Comment by johnkoehn** [comment]
Thanks @wadey
