### ISSUE TITLE
Install Microtime fails on LINUX since 3.1.0

### ISSUE THREAD

**Issue by dlarr** [wadey/node-microtime#71]
Hello, 

I am working behind a corporate proxy. 
Installing microtime on a windows OS works fine.
Version 3.0.0 was also fine

But our CI is hosted on Jenkins + Linuxes

The install fails apparently because the node headers call and we uses a corporate proxy
` gyp http GET https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz`

Apparently, node-gyp enable proxyURL : https://github.com/nodejs/node-gyp#option-2
![image](https://user-images.githubusercontent.com/2865021/196209706-7f791e75-129f-4a16-9b5e-e98d93e17a8d.png)

Any idea on what to do ? 

Logs of the error below.
$ npm install microtime@3.1.0 --verbose
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'microtime@3.1.0',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@7.24.1
npm info using node@v14.18.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/home/jenkins/test/.npmrc Completed in 1ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/jenkins/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 1ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 12ms
npm timing npm:load:configload Completed in 12ms
npm timing npm:load:setTitle Completed in 0ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:cleanupLog Completed in 3ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 1ms
npm timing npm:load Completed in 28ms
npm timing arborist:ctor Completed in 1ms
npm timing arborist:ctor Completed in 0ms
npm timing idealTree:init Completed in 13ms
npm timing idealTree:userRequests Completed in 4ms
npm http fetch GET 200 ARTIF_URL/artifactory/api/npm/g-npm-89c3/microtime 229ms (cache revalidated)
npm http fetch GET 200 ARTIF_URL/artifactory/api/npm/g-npm-89c3/node-addon-api 82ms (cache revalidated)
npm http fetch GET 200 ARTIF_URL/artifactory/api/npm/g-npm-89c3/node-gyp-build 141ms (cache revalidated)
npm timing idealTree:#root Completed in 386ms
npm timing idealTree:node_modules/microtime Completed in 22ms
npm timing idealTree:node_modules/node-addon-api Completed in 0ms
npm timing idealTree:node_modules/node-gyp-build Completed in 0ms
npm timing idealTree:buildDeps Completed in 424ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 445ms
npm timing reify:loadTrees Completed in 446ms
npm timing reify:diffTrees Completed in 2ms
npm timing reify:retireShallow Completed in 0ms
npm timing reify:createSparse Completed in 4ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 404 ARTIF_URL/artifactory/api/npm/g-npm-89c3/-/npm/v1/security/advisories/bulk 32ms
npm http fetch POST 200 ARTIF_URL/artifactory/api/npm/g-npm-89c3/-/npm/v1/security/audits/quick 39ms
npm timing auditReport:getReport Completed in 77ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 80ms
npm timing reifyNode:node_modules/node-gyp-build Completed in 77ms
npm timing reifyNode:node_modules/node-addon-api Completed in 90ms
npm timing reifyNode:node_modules/microtime Completed in 121ms
npm timing reify:unpack Completed in 122ms
npm timing reify:unretire Completed in 0ms
npm timing build:queue Completed in 1ms
npm timing build:link:node_modules/node-gyp-build Completed in 4ms
npm timing build:link Completed in 5ms
npm info run microtime@3.1.0 install node_modules/microtime node-gyp-build
npm info run microtime@3.1.0 install { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 79ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 1850ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (events.js:400:28)
npm verb stack     at maybeClose (internal/child_process.js:1058:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
npm verb pkgid microtime@3.1.0
npm verb cwd /home/jenkins/test
npm verb Linux 5.10.25-linuxkit
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "microtime@3.1.0" "--verbose"
npm verb node v14.18.0
npm verb npm  v7.24.1
npm ERR! code 1
npm ERR! path /home/jenkins/test/node_modules/microtime
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! internal/modules/cjs/loader.js:1144
npm ERR!   return process.dlopen(module, path.toNamespacedPath(filename));
npm ERR!                  ^
npm ERR!
npm ERR! Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/jenkins/test/node_modules/microtime/prebuilds/linux-x64/node.napi.node)
npm ERR!     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:93:18)
npm ERR!     at load (/home/jenkins/test/node_modules/node-gyp-build/index.js:22:10)
npm ERR!     at Object.<anonymous> (/home/jenkins/test/node_modules/node-gyp-build/build-test.js:19:19)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:950:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR!
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild'
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.18.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb find Python Python is not set from command line or npm configuration
npm ERR! gyp verb find Python Python is not set from environment variable PYTHON
npm ERR! gyp verb find Python checking if "python3" can be used
npm ERR! gyp verb find Python - executing "python3" to get executable path
npm ERR! gyp verb find Python - "python3" is not in PATH or produced an error
npm ERR! gyp verb find Python checking if "python" can be used
npm ERR! gyp verb find Python - executing "python" to get executable path
npm ERR! gyp verb find Python - executable path is "/usr/bin/python"
npm ERR! gyp verb find Python - executing "/usr/bin/python" to get version
npm ERR! gyp verb find Python - version is "3.6.6"
npm ERR! gyp info find Python using Python version 3.6.6 found at "/usr/bin/python"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 14.18.0
npm ERR! gyp verb command install [ '14.18.0' ]
npm ERR! gyp verb install input version string "14.18.0"
npm ERR! gyp verb install installing version: 14.18.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version not already installed, continuing with install 14.18.0
npm ERR! gyp verb ensuring nodedir is created /home/jenkins/.cache/node-gyp/14.18.0
npm ERR! gyp verb created nodedir /home/jenkins/.cache/node-gyp/14.18.0
npm ERR! gyp http GET https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp verb command remove [ '14.18.0' ]
npm ERR! gyp verb remove using node-gyp dir: /home/jenkins/.cache/node-gyp
npm ERR! gyp verb remove removing target version: 14.18.0
npm ERR! gyp verb remove removing development files for version: 14.18.0
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
npm ERR! gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
npm ERR! gyp ERR! stack network settings.
npm ERR! gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:170:21)
npm ERR! gyp ERR! stack     at Request.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:877:8)
npm ERR! gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:475:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:106:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! gyp ERR! System Linux 5.10.25-linuxkit
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/jenkins/test/node_modules/microtime
npm ERR! gyp ERR! node -v v14.18.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm verb exit 1
npm timing npm Completed in 2110ms
npm verb unfinished npm timer reify 1666014516727
npm verb unfinished npm timer reify:build 1666014517356
npm verb unfinished npm timer build 1666014517357
npm verb unfinished npm timer build:deps 1666014517357
npm verb unfinished npm timer build:run:install 1666014517364
npm verb unfinished npm timer build:run:install:node_modules/microtime 1666014517365
npm verb code 1

**Comment by wadey** [comment]
The error here is a failure to download the node headers

    npm ERR! gyp http GET https://nodejs.org/download/release/v14.18.0/node-v14.18.0-headers.tar.gz
